namespace: stnvivanco92-dev

app:
  name: frontend
  role: frontend
  image: savivancofi/frontend
  tag: v2
  replicas: 1
  containerPort: 3000
  servicePort: 80
  createRoute: true

env:
  - name: ROLE
    value: frontend
  - name: BACKEND_API_URL
    value: "http://backend-api-svc:8080"